# Generated by Django 5.1.7 on 2025-03-30 20:53

import apps.store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenproducto',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to=apps.store.models.upload_to, verbose_name='Imagen principal'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagenes_secundarias',
            field=models.ManyToManyField(blank=True, related_name='productos', to='store.imagenproducto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nro_referencia',
            field=models.CharField(default=apps.store.models.generar_nro_referencia_unico, editable=False, max_length=6, unique=True),
        ),
    ]
