# Generated by Django 5.1.7 on 2025-03-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_imagenproducto_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('HERRAMIENTAS_MANUALES', 'Herramientas Manuales'), ('HERRAMIENTAS_ELECTRICAS', 'Herramientas Eléctricas'), ('PINTURAS', 'Pinturas'), ('MATERIALES_ELECTRICOS', 'Materiales Eléctricos'), ('SEGURIDAD', 'Artículos de Seguridad'), ('FIJACION', 'Artículos de Fijación'), ('FERRETERIA', 'Ferretería General'), ('JARDIN', 'Jardín y Exteriores')], default='FERRETERIA', max_length=50, verbose_name='Categoría del producto'),
        ),
    ]
