# Generated by Django 5.1.7 on 2025-03-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='disponible',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
